### ISSUE TITLE
妻みぐいSA.ALD   is not getting decompiled. 

### ISSUE THREAD

**Issue by subaru471171** [kichikuou/xsys35c#10]
you have written that 妻みぐい is supported buts it not getting decompiled. 
![image](https://github.com/user-attachments/assets/62cd7660-9440-4116-9415-407b3876b516)

**Comment by kichikuou** [comment]
Which version of the game do you have?

I confirmed that the CD-ROM package version of the game decompiles, but maybe the download version has a different data format for System39.ain.

**Comment by kichikuou** [comment]
Could you run the following command and paste the results?

```
PowerShell -Command "Get-Content System39.ain -Encoding Byte -TotalCount 64 | Format-Hex
```

**Comment by subaru471171** [comment]
![image](https://github.com/user-attachments/assets/a93c62d1-bcf5-4a2a-9910-655e6f29def4)

**Comment by kichikuou** [comment]
I think I was able to fix it. Please download the latest version from [here](https://github.com/kichikuou/xsys35c/actions/runs/12327421793), try to decompile the game and let me know the result.

**Comment by subaru471171** [comment]
Can you give me the builded version?

**Comment by kichikuou** [comment]
You can find the exe here. You must be logged in to GitHub to see the download link.
https://github.com/kichikuou/xsys35c/actions/runs/12327421793

**Comment by subaru471171** [comment]
Do you how to change the font for this game https://vndb.org/v303
It doesnt have any fnl file. 
i am sending you the ain file
[だぶる先生らいふ.zip](https://github.com/user-attachments/files/18178299/default.zip)
Can you see if it contains method of how to change the font.
if not which file contains the font???
![image](https://github.com/user-attachments/assets/e149f974-be21-4048-acc7-9e219d76ffd4)

**Comment by kichikuou** [comment]
Before that, could you please confirm if you were able to successfully decompile 妻みぐい with the fixed build?
https://github.com/kichikuou/xsys35c/actions/runs/12327421793

The download link is here:
<img width="775" alt="link" src="https://github.com/user-attachments/assets/86b6b657-d9cf-44ae-a5b2-48e49b99fa7a" />

**Comment by subaru471171** [comment]
Yes . It has been Successful

**Comment by subaru471171** [comment]
> Do you how to change the font for this game https://vndb.org/v303 It doesnt have any fnl file. i am sending you the ain file [だぶる先生らいふ.zip](https://github.com/user-attachments/files/18178299/default.zip) Can you see if it contains method of how to change the font. if not which file contains the font??? ![image](https://private-user-images.githubusercontent.com/179869621/396852362-e149f974-be21-4048-acc7-9e219d76ffd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1Mjc5NzgsIm5iZiI6MTczNDUyNzY3OCwicGF0aCI6Ii8xNzk4Njk2MjEvMzk2ODUyMzYyLWUxNDlmOTc0LWJlMjEtNDA0OC1hY2M3LTllMjE5ZDc2ZmZkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQxMzE0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzlkZjM5MGIxOWZhYmM0NTBlZjQ3MzY2NDA0MjM0Nzg0OWNjMjI3MmU3N2Y0NTFlZWJlMjdmNDdjMzA0MTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2N9sAC5ffqrtg2x3kJXA-n1XGtl6XTrz5qQ0Lh2YGNQ)

Do you have any idea how to do it?

**Comment by kichikuou** [comment]
This repository is for xsys35c, a compiler for System3.5 - 3.9 games. だぶる先生らいふ uses a different engine, so I can't help with font modification for that game.
(Edited your comment removing the link to a copyrighted file)

**Comment by subaru471171** [comment]
Noted thanks.
