### ISSUE TITLE
Guide with the decompiled source code

### ISSUE THREAD

**Issue by fcolecumberri** [kichikuou/xsys35c#2]
This might not be he best place to ask this, but I havn't found a better place to ask it.

I have been analyzing a decompiled game (because I want to translate it), and I more less can understand what's happening by reading the files and comparing that with what is happening on the game.

However there are several parts when I became a little bit lost, so I was wondering if you have an English guide about how to navigate a decompiled game files (I don't understand Japanese very well so I might have already seen a jap guide without even realizing it is a guide).

If you don't have any guide I might make one using the notes I am taking, but then I have some specific questions I can't find answers, I would love if you could enlighten me a little.

for example:

I have noticed that: `~ZACG 201, SP_EF, SP_EFWA:` means `character 201` enters the scene on the right side (ZBCG means left side) and even though, I know who is  `character 201` because I have played the game enough to know who `201` is; I don't have the relationship list of every character and I assume the list might exist in one of the 200 decompiled files. I just have no idea where it is. Do you know where the list is?

P.S.: if someone is wondering how I want to translate a jap game without understanding jap, is because I know people that know jap, but have no idea about programming. So... teamwork.

**Comment by fcolecumberri** [comment]
Ok, now I understand that `~ZACG 201, SP_EF, SP_EFWA:` means put the character CG 201 at the right, but in the game it also puts the character's name over the character CG (which I know it is not another CG over the first CG because when fonts where missing, the name was also missing https://github.com/kichikuou/xsystem35-sdl2/issues/21 ). Also I have no idea what `SP_EF, SP_EFWA` indicates.

**Comment by kichikuou** [comment]
Unfortunately I am not aware of any such guide. In Japan, game modding is not very popular. I don't know much about the English community, so you might want to ask on the [Wiki](https://alicesoft.fandom.com/). The people there know more about the decompiled code than I do.

To know what is going on in the code, it is essential to understand the System3.x language. Check out the System3.5 programming resources page (especially the SDK manual) on the Wiki if you haven't:
https://alicesoft.fandom.com/wiki/User_blog:RottenBlock/System_Programming_Resources#System_3.5

`~ZACG 201, SP_EF, SP_EFWA:` means a call to the function `ZACG` with `201`, `SP_EF` and `SP_EFWA` as arguments. So to understand what it does, we need to look at the definition of the function. Function definitions start with `**`, so `grep` command can be used to find them.

```sh
$ grep '\*\*ZACG' *.ADV
SUBCALL.ADV:**ZACG F01, F02, F03:
```

In the `ZACG` function, parameters `F01` - `F03` are copied to local variables `D01` - `D03` (`NB D01, F01, 3:`). Values of `SP_EF` and `SP_EFWA` are assigned to `D02` and `D03` respectively, and used here:

```
    CE 0, VY, 272, 448, 0, 0, D02, D03, 0:
```

The 7th and 8th parameters of the `CE` command are `effect_number` and `option`. This is the meaning of `SP_EF` and `SP_EFWA`.

How is the character's name determined? In `ZACG`, the CG number (201) is set to the `ACG_NO` variable. It is used below as an argument to the `ＳＰ名前` function.

```
        ~ＳＰ名前 ACG_NO, 1501, 1502:
```

This function is a bit complicated and I haven't followed it in detail, but it seems that this function sets the name (e.g. `山本 悪司`) to the string variable 1501 and the furigana (e.g. `ヤマモト アクジ`) to the string variable 1502.

**Comment by fcolecumberri** [comment]
What you just told me is just perfect, I thought `ZACG` was an internal system3.x function, but now that I know that functions are defined with `**foo` and `~foo bar ...:` are function calls, this gives me much more info. Thanks.

This is just perfect, it gives me tons of info specially because know I see functions that are in your code like `MsgSkip.SetAction`. I was so confused about how this works, thanks.

Also, I am just seeing the Sys39SDK manual, from the wiki, about the programming language (which I would love to be able to understand), I will try to check those first and only if I still have problems, I will ask you. THANKS!!
