### ISSUE TITLE
Rance II error when decompiling and no files for Unicode Mode

### ISSUE THREAD

**Issue by Cerzs** [kichikuou/xsys35c#4]
Hello there! I'm getting an error when decompiling:

`Assertion failed: is_sjis_byte1(c), file decompiler/decompile.c, line 141`.

Some files can be extracted, but no `xsys35c.cfg` is generated. I'm using [latest patched version](https://alicesoft.fandom.com/wiki/User_blog:Velt211/Rance_II_translation_port_release).

Thank you!

**Comment by Cerzs** [comment]
I was using latest version _released_, using the version from my last issue works so nevermind, I guess?

**Comment by kichikuou** [comment]
Hmm, it seems to be a more common issue than I thought.
I just released [version 1.8.1](https://github.com/kichikuou/xsys35c/releases/tag/v1.8.1) including the fix for this issue.

**Comment by Cerzs** [comment]
Hey there, @kichikuou. I'm reopening this, as I'm having a similar problem with IV when using [fix fan-patch](https://alicesoft.fandom.com/wiki/User_blog:RottenBlock/Rance_IV_Fan-Patch.)

This time there is no error, when running the new ALD, the game just crashed right after running.

**Comment by RottenBlock** [comment]
I just decompiled and recompiled the patch with xsys35, and didn't see this error. Did you change anything before recompiling?

**Comment by Cerzs** [comment]
@RottenBlock Just added the "unicode = true" in xsys35c.cfg

**Comment by Cerzs** [comment]
After some checking, I decided to change the name. Normally I would add an "-ex" to differentiate the new one, (Name-ex.ald), it seems that this breaks something, because removing it starts normal. I don't know if it's a bug, but I'm reporting it anyway

**Comment by kichikuou** [comment]
xsystem35 loads the first `xxxSA.ALD` file found in the folder. `xxx-ex.ald` is not used.

If you keep the original (non-unicode) `xxxSA.ALD` in the folder, it is loaded along with the unicode version of `System39.ain`. This will cause garbled characters or crashes.
