### ISSUE TITLE
UTF8 not rendering special characters

### ISSUE THREAD

**Issue by fcolecumberri** [kichikuou/xsys35c#7]
I am trying to recompile Daiakuji with Spanish characters, for this I have already added to `.xsys35rc` the lines:

```
ttfont_gothic: /usr/share/fonts/Unifont/Unifont_jp.otf
ttfont_mincho: /usr/share/fonts/Unifont/Unifont_jp.otf
```
and set `xsys35c.cfg` with:

```
ald_basename = 大悪司
output_ain = System39.ain
hed = xsys35dc.hed
variables = variables.txt
sys_ver = 3.9

encoding = utf8
unicode = true
```

However after I recompile using `xsys35c` and run it with `xsystem35` the special characters don't appear.

![screenshot_trim](https://github.com/kichikuou/xsys35c/assets/12193875/d56ceb70-b19d-496a-9c49-bb1877180e7f)

Here you can see that `asociación` and `gestión` are not fully rendered.

Thanks for your awesome toolkit.

**Comment by kichikuou** [comment]
The font in the screenshot does not appear to be Unifont.
Make sure the `.xsys35rc` file is in `$HOME`, or in the current directory when you run `xsystem35`. (`.xsys35rc` in the current directory overrides `$HOME/.xsys35rc`.)

**Comment by fcolecumberri** [comment]
Ok, I thought that the `.xsys35rc` needed to be on the compile directory, not on the run directory, thanks.
